Moved messages to STDERR and added gzip dumper

diff --git a/scripts/mysql/table-dump b/scripts/mysql/table-dump
--- a/scripts/mysql/table-dump
+++ b/scripts/mysql/table-dump
@@ -1,13 +1,12 @@
 #!/bin/sh
 
 if [ $# -lt 1 ]; then
-	echo "Usage: $0 table_name [additional arguments for mysqldump]"
+	>&2 echo "Usage: $0 table_name [additional arguments for mysqldump] > table_name.sql"
 	exit 1
 fi
 
 COMMAND=$0
 COMMAND_PATH=`pwd -P`
-# >&2 echo $COMMAND_PATH
 
 FULL_ARGS=$@
 TABLE=$1
@@ -16,13 +15,13 @@ ARGS=$@
 
 DB=`$COMMAND_PATH/database-get`
 if [ $? -ne 0 ]; then
-	echo "Error: Unable to fetch database name"
+	>&2 echo "Error: Unable to fetch database name"
 	exit 1
 fi
 
 TABLE_VERSION=`$COMMAND_PATH/config-get-value $TABLE`
 if [ $? -ne 0 ]; then
-	echo "Error: Unable to fetch table version from config"
+	>&2 echo "Error: Unable to fetch table version from config"
 	exit 1
 fi
 
diff --git a/scripts/mysql/table-load-gzip b/scripts/mysql/table-load-gzip
--- a/scripts/mysql/table-load-gzip
+++ b/scripts/mysql/table-load-gzip
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ $# -lt 1 ]; then
-	echo "Usage: $0 my_database_file.sql.gz [other arguments to mysql]"
+	>&2 echo "Usage: $0 my_database_file.sql.gz [other arguments to mysql]"
 	exit 1
 fi
 
@@ -14,7 +14,7 @@ ARGS=$@
 
 DB=`$COMMAND_PATH/database-get`
 if [ $? -ne 0 ]; then
-	echo "Error: Unable to fetch database name"
+	>&2 echo "Error: Unable to fetch database name"
 	exit 1
 fi
 
